import js from "@eslint/js";
import stylistic from "@stylistic/eslint-plugin";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import globals from "globals";

export default [
	js.configs.recommended,
	{
		"languageOptions": {
			"ecmaVersion": 2022,
			"globals": {
				...globals.es2022,
			},
			"sourceType": "module",
		},
		"plugins": {
			"@stylistic": stylistic,
			"simple-import-sort": simpleImportSort,
		},
		"rules": {
			"@stylistic/array-bracket-newline": ["error", "consistent"],
			"@stylistic/array-bracket-spacing": ["error", "never"],
			"@stylistic/arrow-parens": ["error", "as-needed"],
			"@stylistic/arrow-spacing": ["error"],
			"@stylistic/block-spacing": ["error", "always"],
			"@stylistic/brace-style": ["off"],
			"@stylistic/comma-dangle": ["error", "always-multiline"],
			"@stylistic/comma-spacing": ["off"],
			"@stylistic/comma-style": ["error", "last"],
			"@stylistic/computed-property-spacing": ["error", "never"],
			"@stylistic/eol-last": ["error", "always"],
			"@stylistic/function-call-spacing": ["off"],
			"@stylistic/function-paren-newline": ["error", "multiline"],
			"@stylistic/indent": ["error", "tab"],
			"@stylistic/key-spacing": ["error", { "afterColon": true, "beforeColon": false, "mode": "strict" }],
			"@stylistic/keyword-spacing": ["off"],
			"@stylistic/linebreak-style": ["error", "unix"],
			"@stylistic/lines-around-comment": ["error", { "afterBlockComment": false, "beforeBlockComment": true }],
			"@stylistic/lines-between-class-members": ["off"],
			"@stylistic/multiline-ternary": ["error", "never"],
			"@stylistic/new-parens": ["error"],
			"@stylistic/no-extra-parens": ["off"],
			"@stylistic/no-mixed-operators": ["error"],
			"@stylistic/no-mixed-spaces-and-tabs": ["error"],
			"@stylistic/no-multi-spaces": ["error", { "ignoreEOLComments": false }],
			"@stylistic/no-multiple-empty-lines": ["error", { "max": 2, "maxBOF": 0, "maxEOF": 1 }],
			"@stylistic/no-tabs": ["error", { "allowIndentationTabs": true }],
			"@stylistic/no-trailing-spaces": ["error", { "ignoreComments": true }],
			"@stylistic/no-whitespace-before-property": ["error"],
			"@stylistic/nonblock-statement-body-position": ["error", "beside"],
			"@stylistic/object-curly-spacing": ["off"],
			"@stylistic/padding-line-between-statements": [
				"error",
				{ "blankLine": "always", "next": "return", "prev": "*" },
				{ "blankLine": "always", "next": "*", "prev": ["const", "let"] },
				{ "blankLine": "any", "next": ["const", "let", "if", "try"], "prev": ["const", "let"] },
			],
			"@stylistic/quote-props": ["error", "as-needed"],
			"@stylistic/quotes": ["error", "double"],
			"@stylistic/semi": ["error", "always"],
			"@stylistic/semi-spacing": ["error", { "after": true, "before": false }],
			"@stylistic/semi-style": ["error", "last"],
			"@stylistic/space-before-blocks": ["error", "always"],
			"@stylistic/space-before-function-paren": ["off"],
			"@stylistic/space-in-parens": ["error", "never"],
			"@stylistic/space-infix-ops": ["off"],
			"@stylistic/space-unary-ops": ["error", { "nonwords": false, "words": true }],
			"@stylistic/spaced-comment": ["error", "always"],
			"@stylistic/template-tag-spacing": ["error", "never"],
			"arrow-body-style": ["error", "as-needed"],
			"consistent-this": ["error", "that"],
			"eqeqeq": ["warn", "always"],
			"func-style": ["error", "declaration", { "allowArrowFunctions": true }],
			"id-length": ["error", { "exceptions": ["_", "cb", "el", "i", "i2", "id", "ID", "t", "to"], "min": 3 }],
			"new-cap": ["error"],
			"no-dupe-args": ["error"],
			"no-dupe-keys": ["error"],
			"no-invalid-regexp": ["error"],
			"no-irregular-whitespace": ["error", { "skipComments": true, "skipRegExps": true, "skipStrings": true, "skipTemplates": true }],
			"no-lonely-if": ["error"],
			"no-redeclare": ["off"],
			"no-sequences": ["error"],
			"no-shadow": ["off"],
			"no-underscore-dangle": ["off"],
			"no-unexpected-multiline": ["error"],
			"no-unreachable": ["error"],
			"no-unused-expressions": ["off"],
			"no-unused-vars": ["off"],
			"no-use-before-define": ["off"],
			"no-var": ["error"],
			"one-var": ["error", "never"],
			"prefer-arrow-callback": ["error"],
			"simple-import-sort/imports": ["error"],
			"sort-imports": ["off"],
			"sort-keys": ["error", "asc", { "caseSensitive": true, "minKeys": 2, "natural": true }],
			"sort-vars": ["error"],
			"strict": ["error", "global"],
			"unicode-bom": ["error", "never"],
			"valid-typeof": ["error"],
			"vars-on-top": ["off"],
		},
	},
];
